# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmFmMGZiYWUwNDM1MTMyMjAyYjgxY2RiN2JmMjg1ZjMyMTAzZmFkOGQ3NjE0Y2IyOTg4ODg2Yjg1MmM4MmNjZTVjNjE3M2I0MTRkZDliMGY0NmY2OGM3MGY5NmZiYTZlYTI5ZmI1M2M2YWM1YjBjMjA0OWJiYzMxZGVjMWRkNGI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
